export const books = [
  {
    sno: "1",
    title: "ps1",
    author: "raja",
    copies: "20",
    status: "available",
    actions: "",
  },
  {
    sno: "2",
    title: "ps2",
    author: "raja",
    copies: "20",
    status: "available",
    actions: "",
  },
  {
    sno: "3",
    title: "ps1",
    author: "raja",
    copies: "20",
    status: "available",
    actions: "",
  },
  {
    sno: "4",
    title: "ps1",
    author: "raja",
    copies: "20",
    status: "available",
    actions: "",
  },
  {
    sno: "5",
    title: "ps1",
    author: "raja",
    copies: "20",
    status: "available",
    actions: "",
  },
];
